services:
  mysql:
    image: 'mysql:9.3.0'
    environment:
      - 'MYSQL_DATABASE=tarefas'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
